### ISSUE TITLE
example command doesn't work

### ISSUE THREAD

**Issue by infothrill** [Incognito/python-architecture-linter#13]
In the README:
```
poetry run python python_architecture_linter_cli/run.py /home/brian/target-project/
```

Expected outcome: some form of linter output.

Actual outcome:
```
python: can't open file 'python_architecture_linter_cli/run.py': [Errno 2] No such file or directory
```

**Comment by Incognito** [comment]
Thanks, I wrote that before I moved some packages around and haven't updated it yet.

The new runtime concept is more complex, the idea is you write the script in your project. If you want to try the demo_project cli it will do the same thing.

I'll close this after I've fixed the docs -- I want to move some more walls around: I want to distribute multiple packages from the monorepo.

**Comment by Incognito** [comment]
Please see https://github.com/Incognito/python-architecture-linter-demo/ which consumes the libs.
